### ISSUE TITLE
Could the method be outside of the DLL ?

### ISSUE THREAD

**Issue by goldenbr0wn** [einaregilsson/InjectModuleInitializer#11]
I want to mod a game for which I don't have the source code of a DLL, is it possible for the method to be outside of the DLL or to inject the method in the DLL ?

**Comment by einaregilsson** [comment]
It's not possible for the method to be outside the dll or to inject the method into the dll right now. It would be possible to change the code to allow that, but you'd have to do that on your own, I'm not really adding any more features to this project.
