### ISSUE TITLE
Error when compiling in Visual Studio 2015

### ISSUE THREAD

**Issue by alexfoxgill** [einaregilsson/InjectModuleInitializer#7]
When building a project with InjectModuleInitializer installed in Visual Studio 2015 (or MSBuild v14.0) the following error is encountered:

> InjectModuleInitializer v1.3
> EXEC : error : Unknown custom metadata item kind: 6
> error MSB3073: The command "C:\www\myproject\packages\InjectModuleInitializer.1.3.1\tools\InjectModuleInitializer.exe "C:\www\myproject\Tests\bin\Debug\myproject.dll"" exited with code 1.

**Comment by einaregilsson** [comment]
Ok, does VS2015 come with a new CLR? I don't really do much .NET anymore so I haven't looked into it, but I'll try to take a look sometime this week. There might be a new version of Mono.Cecil out, the library I use to change the metadata.

**Comment by alexfoxgill** [comment]
Yeah it's .net 4.6 with C# v6 that I'm trying to compile in. Thanks for looking into it, much appreciated

**Comment by einaregilsson** [comment]
Well, looked into it and yes, I needed an updated version of Mono.Cecil. Have published v1.4 through NuGet, you can get it from there. Let me know if you still have problems.

**Comment by alexfoxgill** [comment]
Fantastic, thanks!
