### ISSUE TITLE
possible bug when compiling in 2015 on a project with Newtonsoft.

### ISSUE THREAD

**Issue by killyosaur** [einaregilsson/InjectModuleInitializer#8]
I get a "Cannot resolve Assembly" error for Newtonsoft.json when running this after compiling my project. Have not checked to see if this error occurs in 2013, and not sure if it has to do with the version of Newtonsoft (using the most current version, 7.01).

**Comment by killyosaur** [comment]
the error message is "Failed to resolve Assembly"

**Comment by einaregilsson** [comment]
That sounds weird. Has it worked with other assemblies in the same setup?
